#!/bin/bash

tempfile=$(mktemp)

for FILE in $(git diff --cached --name-only | sed 's| |\\ |g')
   do
      if [[ ($FILE == *.c) || ($FILE == *.h) ]]
      then
         clang-format $FILE > "$tempfile"
         mv "$tempfile" "$FILE"
         git add "$FILE"
      fi
   done

trap '{ rm -f -- "$tempfile"; }' EXIT
