name: Test Compile Code 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: latest
      - name: configure
        run: make
      - name: compile
        run: make
      - name: test
        run: make test
